def test_full_pipeline(built_project):
    target, summary = built_project
    assert summary["synthetic_referrals"] > 1000
    assert summary["open_actions"] >= 1
    assert (target / "reports/executive_dashboard.html").exists()
    assert (target / "reports/monthly_control_pack.md").exists()
    assert (target / "results/scenario_impact.csv").exists()
    assert (target / "results/resource_optimisation.csv").exists()
    assert (target / "results/experiment_design.csv").exists()
    assert (target / "results/service_level_status.csv").exists()
    assert summary["pareto_resource_plans"] >= 1
    assert summary["contract_rules_failed"] == 0
    assert (target / "results/run_manifest.json").exists()
    assert (target / "results/queue_policy_comparison.csv").exists()
    assert (target / "results/incident_register.csv").exists()
    assert (target / "results/root_cause_scorecard.csv").exists()
    assert (target / "results/ds_question_catalog.csv").exists()
    assert (target / "reports/ds_question_casebook.md").exists()
    assert (target / "reports/evidence_backed_ds_handbook.md").exists()
    assert (target / "results/evidence_registry.csv").exists()
    assert (target / "results/evidence_coverage.csv").exists()
    assert (target / "results/kpi_uncertainty.csv").exists()
    assert summary["ds_questions_covered"] == 106
